import { appidstep1, appidstep2, appidstep3, appidstep4, appidstep5, appidstep6, appidstep7, appidstep8, appidstep9, awsstep1, awsstep2, awsstep3, awsstep4, awsstep5, awsstep6, awsstep7, awsstep8, awsstep9, devOpsstep1,devOpsstep2,devOpsstep3,devOpsstep4,devOpsstep5,devOpsstep6,devOpsstep7,devOpsstep8,devOpsstep9,devOpsstep10,devOpsstep11,devOpsstep12 , githubstep10, githubstep11, githubstep12, githubstep2, githubstep3, githubstep4, githubstep5, githubstep6, githubstep7, githubstep8, githubstep9, ibmChatstep1, ibmChatstep2, ibmChatstep3, ibmChatstep4, ibmChatstep5, ibmChatstep6, ibmChatstep7, ibmChatstep8, ibmChatstep9, githubstep1, } from "../assets";

const TUTORIAL = {
  AppId: {
    title: "IBM App ID",
    icon: "🔐",
    color: "#00e5ff",
    image:[appidstep1,appidstep2,appidstep3,appidstep4,appidstep5,appidstep6,appidstep7,appidstep8,appidstep9],
    description:
      "IBM App ID is a cloud-based identity and access management service that provides authentication and authorization capabilities for applications. It allows developers to easily integrate user authentication and access control into their applications, enabling secure access to resources and data. With IBM App ID, developers can implement various authentication methods, such as social login, email/password, and multi-factor authentication, to enhance the security of their applications.",
    steps: [
      "Open IBM Cloud: https://cloud.ibm.com/login — Login with your IBM ID or create a new account if you don't have one.",
      "Open Dashboard: https://cloud.ibm.com/dashboard/apps — Click on Create Resource → Search for App ID.",
      "Click on App ID → Click on Create Resource → Select Region → Choose Lite Plan → Click on Create.",
      "Create Service: Select Region → Choose Lite Plan → Click on Create → Wait for the service to be provisioned and become active.",
      "Launch Watson Assistant → Click on Create an App ID → Wait for the App ID to be created and become active.",
      "Create App ID: Enter Name → Click Create → Wait for the App ID to become active. Click the App ID name to access its dashboard.",
      "View App ID: Click on View Credentials → Copy Client ID and Secret — keep them secure and do not share publicly.",
      "Use Credentials: Use Client ID and Secret in your application to authenticate users and manage access control.",
      "Manage App ID: Monitor usage metrics, manage authentication methods, configure user management settings, and set up access control policies.",
      "Documentation: https://cloud.ibm.com/docs/appid?topic=appid-getting-started — Comprehensive info on authentication methods, user management, and access control policies.",
    ],
  },
  ChatBot: {
    title: "IBM ChatBot",
    icon: "🤖",
    color: "#a78bfa",
    image:[ibmChatstep1,ibmChatstep2,ibmChatstep3,ibmChatstep4,ibmChatstep5,ibmChatstep6,ibmChatstep7,ibmChatstep8, ibmChatstep9],
    description:
      "IBM ChatBot is a conversational AI platform that allows developers to create and deploy chatbots for various applications and use cases. It provides tools and services for building, training, and managing chatbots that can interact with users in natural language. With IBM ChatBot, developers can create chatbots that understand and respond to user queries, provide information, perform tasks, and engage in conversations across multiple channels such as websites, messaging platforms, and mobile apps.",
    steps: [
      "Open IBM Cloud: https://cloud.ibm.com/login — Login with your IBM ID or create a new account.",
      "Open Dashboard: https://cloud.ibm.com/dashboard/apps — Click on Create Resource → Search for ChatBot.",
      "Click on ChatBot → Click on Create Resource → Select Region → Choose Lite Plan → Click on Create.",
      "Create Service: Select Region → Choose Lite Plan → Click on Create → Wait for the service to become active.",
      "Launch Watson Assistant → Click on Create a ChatBot → Wait for the ChatBot to be created and become active.",
      "Create ChatBot: Enter Name → Click Create → Wait for the ChatBot to become active.",
      "View ChatBot: Click on View Credentials → Copy Client ID and Secret — keep them secure.",
      "Use Credentials: Use Client ID and Secret in your application to authenticate users.",
      "Manage ChatBot: Monitor usage metrics, manage authentication methods, configure settings.",
      "Documentation: https://cloud.ibm.com/docs/assistant?topic=assistant-getting-started",
    ],
  },
  GitHub: {
    title: "GitHub",
    icon: "🐙",
    color: "#f97316",
    image:[githubstep1,githubstep2,githubstep3,githubstep4,githubstep5,githubstep6,githubstep7,githubstep8,githubstep9,githubstep10,githubstep11,githubstep12],
    description:
      "GitHub is a web-based platform that provides hosting for Git repositories and offers additional features for collaboration and project management. With GitHub, developers can easily manage their codebase, track changes, and collaborate with other developers on projects. GitHub provides a user-friendly interface for managing repositories, issues, pull requests, and more.",
    steps: [
      "Install Git: Download from https://git-scm.com/downloads and verify with git --version in terminal.",
      "Create GitHub Account: Go to https://github.com/signup and fill in username, email, and password.",
      "Create Repository: Click 'New' → provide a name, choose public/private, and click 'Create repository'.",
      "Clone Repository: Click 'Code' → copy URL → run: git clone <repository-url> in your terminal.",
      "Make Changes: Use a code editor to edit files in your local cloned repository.",
      "Commit Changes: Run git add . then git commit -m 'Your commit message' to save changes locally.",
      "Push Changes: Run git push origin main to upload your committed changes to GitHub.",
      "Create Pull Request: Click 'Pull requests' → 'New pull request' → select branch → submit for review.",
      "Review & Merge: Review proposed changes, leave comments, approve and click 'Merge pull request'.",
      "Documentation: https://docs.github.com/en — comprehensive GitHub usage and version control guidance.",
    ],
  },
  AWS: {
    title: "AWS Cloud Foundations",
    icon: "☁️",
    color: "#f59e0b",
    image:[awsstep1,awsstep2,awsstep3,awsstep4,awsstep5,awsstep6,awsstep7,awsstep8,awsstep9],
    description:
      "Amazon Web Services (AWS) is a comprehensive cloud computing platform provided by Amazon. It offers a wide range of services, including computing power, storage, databases, machine learning, analytics, and more. AWS allows businesses and developers to build and deploy applications in the cloud, providing scalability, reliability, and security. Users can access resources on-demand and pay only for what they use.",
    steps: [
      "Create AWS Account: Go to https://aws.amazon.com/ → click 'Create a Free Account' and follow the prompts.",
      "Access AWS Management Console: Log in at https://aws.amazon.com/console/ to manage and configure services.",
      "Explore AWS Services: Browse Compute, Storage, Database, Machine Learning, Analytics sections and more.",
      "Create Resources: Navigate to your desired service → configure and launch resources like EC2, S3, or Lambda.",
      "Manage Resources: Monitor status, stop/terminate instances, manage permissions, and update configurations.",
      "Monitor and Optimize: Use CloudWatch for monitoring and AWS Cost Explorer to analyze and reduce spending.",
      "Security Best Practices: Use IAM for access control, enable encryption, and monitor for threats regularly.",
      "Scale and Deploy: Use Auto Scaling, Elastic Load Balancing, Elastic Beanstalk, or Lambda for deployments.",
      "Support and Resources: Access AWS Support Center, forums, documentation, and training resources.",
      "Documentation: https://docs.aws.amazon.com/ — comprehensive AWS usage, architecture, and best practices.",
    ],
  },
  DeVops: {
    title: "DevOps Engineering",
    icon: "⚙️",
    color: "#10b981",
    image:[devOpsstep1,devOpsstep2,devOpsstep3,devOpsstep4,devOpsstep5,devOpsstep6,devOpsstep7,devOpsstep8,devOpsstep9,devOpsstep10,devOpsstep11,devOpsstep12],
    description:
      "DevOps is a set of practices and cultural philosophies that aim to improve collaboration and communication between software development (Dev) and IT operations (Ops) teams. It emphasizes automation, continuous integration and delivery (CI/CD), and a culture of shared responsibility for the entire software development lifecycle. DevOps aims to increase the speed and quality of software delivery while ensuring stability and reliability in production environments.",
    steps: [
      "Understand DevOps Principles: Learn collaboration, automation, CI/CD, and shared responsibility mindset.",
      "Assess Your Current Processes: Evaluate workflows, tools, and communication to identify bottlenecks.",
      "Choose the Right Tools: Select version control, CI/CD pipelines, config management, and monitoring tools.",
      "Implement Automation: Automate build, deployment, infrastructure provisioning, testing, and monitoring.",
      "Foster Collaboration: Break down silos with regular meetings, shared docs, and cross-functional teams.",
      "Implement CI/CD: Set up pipelines to automate build, testing, and deployment for faster releases.",
      "Monitor and Measure: Use monitoring/logging solutions and establish KPIs to measure DevOps success.",
      "Embrace Continuous Improvement: Encourage learning, experimentation, and iterative optimization.",
      "Provide Training and Support: Give teams access to training, workshops, and mentorship for DevOps skills.",
      "Documentation: https://www.atlassian.com/devops — comprehensive DevOps implementation guidance.",
    ],
  },
  Docker: {
    title: "Docker & Containers",
    icon: "🐳",
    color: "#0ea5e9",
    image:[devOpsstep1,devOpsstep2,devOpsstep3,devOpsstep4,devOpsstep5,devOpsstep6,devOpsstep7,devOpsstep8,devOpsstep9,devOpsstep10,devOpsstep11,devOpsstep12],
    description:
      "Docker is an open-source platform that allows developers to automate the deployment of applications inside lightweight, portable containers. Containers are isolated environments that package an application and its dependencies together, making it easier to develop, ship, and run applications across different environments. Docker provides a consistent and efficient way to build, test, and deploy applications.",
    steps: [
      "Install Docker: Download from https://www.docker.com/get-started and verify with docker --version.",
      "Create Dockerfile: Write a Dockerfile specifying base image, copying files, installing dependencies.",
      "Build Docker Image: Run docker build -t <image-name> . to create an image from your Dockerfile.",
      "Run Docker Container: Run docker run -d -p <host-port>:<container-port> <image-name> to start a container.",
      "Manage Containers: Use docker ps, docker stop, docker logs, docker exec, and docker rm commands.",
      "Push Docker Image: docker login → docker tag → docker push <username>/<repository-name>:<tag> to Docker Hub.",
      "Pull Docker Image: Run docker pull <username>/<repository-name>:<tag> to download an image locally.",
      "Docker Compose: Create docker-compose.yml to define and manage multi-container applications.",
      "Docker Swarm: Use Docker's native clustering to manage a cluster of Docker nodes as one system.",
      "Documentation: https://docs.docker.com/ — Dockerfiles, images, containers, Compose, and Swarm.",
    ],
  },
  IBMCloudDeployment: {
    title: "IBM Cloud Deployment",
    icon: "🚀",
    color: "#8b5cf6",
    image:[devOpsstep1,devOpsstep2,devOpsstep3,devOpsstep4,devOpsstep5,devOpsstep6,devOpsstep7,devOpsstep8,devOpsstep9,devOpsstep10,devOpsstep11,devOpsstep12],
    description:
      "IBM Cloud Deployment refers to the process of deploying applications and services on the IBM Cloud platform. IBM Cloud provides a range of deployment options, including virtual servers, containers, serverless functions, and more. With IBM Cloud Deployment, developers can easily deploy their applications to the cloud, taking advantage of the scalability, reliability, and security features offered by IBM Cloud.",
    steps: [
      "Prepare Your Application: Package your app, configure dependencies, and verify IBM Cloud requirements.",
      "Choose Deployment Option: Select virtual servers, containers, serverless, or other IBM Cloud options.",
      "Configure Resources: Create virtual servers, configure container clusters, set up serverless functions.",
      "Deploy Your Application: Use IBM Cloud CLI or DevOps tools to deploy your application to the cloud.",
      "Monitor and Manage: Track health and performance using IBM Cloud's monitoring and management tools.",
      "Scale Your Deployment: Adjust allocated resources based on application demand using IBM Cloud scaling features.",
      "Implement Security: Apply access controls, encrypt data, update regularly, and monitor for threats.",
      "Optimize Performance: Identify bottlenecks using performance monitoring tools and make adjustments.",
      "Update and Maintain: Apply patches, update dependencies, and adjust deployment configurations regularly.",
      "Documentation: https://cloud.ibm.com/docs/deploy?topic=deploy-getting-started",
    ],
  },
};

export default TUTORIAL;